---
title: "Empirical Evaluation"
author: Rafael Savvides 
email: rafael.savvides@helsinki.fi
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

This notebook reproduces the figures in the "Empirical evaluation" section.

# Init
```{r message=FALSE}
source("funs/fwer_investing.R")
library(ggplot2)
library(dplyr)
library(purrr)
library(tidyr)
library(stringr)
library(onlineFDR)
library(ggpubr)
DIR_FIGURES = "../../manuscripts/infovis2019/figures"
```

# Expert vs naive user
```{r}
source("run_exp_expert_naive.R", chdir = TRUE)
df_exp_expert_naive = apply(exp_expert_naive$res, c(1,2), mean, na.rm=TRUE) %>% 
  as_tibble() %>% 
  mutate(k = exp_expert_naive$input$K) %>% 
  pivot_longer(-k, names_to="n", values_to="p_mean") %>% 
  mutate(n = as.numeric(map(n, ~gsub("n=", "", .))))
```

```{r}
fig_expert_naive = df_exp_expert_naive %>% 
  ggplot() + theme_minimal()+
  geom_tile(aes(k, n, fill=p_mean), height=0.4) +
  scale_y_log10() + 
  scale_fill_viridis_c(direction=-1)
fig_expert_naive
#ggsave(file.path(DIR_FIGURES, "exp_expert_naive.pdf"), fig_expert_naive, width=6, height=3)
```


# Within-view correction

```{r}
source("run_exp_correlated.R", chdir=TRUE)
```

```{r}
fig_correlated_examples = ggpubr::ggarrange(plot_example(1000, 1, 3), 
                                            plot_example(1000, 10, 3),
                                            plot_example(1000, 100, 3), ncol=1)
fig_correlated_examples
# ggsave(file.path(DIR_FIGURES, "exp_correlated_examples.pdf"), fig_correlated_examples, width = 6, height = 6)
```


```{r}
df_exp_correlated = exp_correlated$result %>% 
  tidyr::pivot_longer(-c(1,2)) %>% 
  dplyr::filter(n==1000) %>% 
  dplyr::mutate(name = stringr::str_remove(name, "pv."), 
                name = forcats::fct_reorder(name, -value, median))
fig_correlated = ggplot(df_exp_correlated) + theme_minimal()+
  geom_line(aes(l, value, color=name, linetype=name), alpha=0.8) + 
  geom_point(aes(l, value, color=name, shape=name), alpha=0.6) + 
  scale_color_manual(values = c("minp"="black", "raw"="grey","bonf"="#1b9e77", 
                                "BH"="#7570b3", "BY"="#d95f02"), 
                     labels = c("minp"="minP", "raw"="None","bonf"="Bonferroni", 
                                "BH"="BH", "BY"="BY")) + 
  scale_shape_manual(values = c("minp"=1, "raw"=4, "bonf"=3, "BH"=2, "BY"=5), 
                     labels = c("minp"="minP", "raw"="None","bonf"="Bonferroni", 
                                "BH"="BH", "BY"="BY")) + 
  scale_linetype_manual(values = c("minp"=1, "raw"=2, "bonf"=2, "BH"=2, "BY"=2), 
                     labels = c("minp"="minP", "raw"="None","bonf"="Bonferroni", 
                                "BH"="BH", "BY"="BY")) + 
  scale_x_log10() + 
  scale_y_log10() + 
  expand_limits(y=1)+
  labs(x="GP length scale", 
       y="", 
       #title=paste0("Outlier p-value (median over ", exp_correlated$args$n_rep, " runs)"), 
       color="",
       shape="",
       linetype="") + 
  theme(legend.position = "bottom")

fig_correlated
#ggsave(file.path(DIR_FIGURES, "exp_correlated.pdf"), fig_correlated, width = 4, height = 4)
```

```{r}
fig_correlated_both = ggpubr::ggarrange(fig_correlated + labs(tag = "(a)") + theme(plot.tag.position = "bottom"), 
                                        fig_correlated_examples + labs(tag = "(b)") + theme(plot.tag.position = "bottom", plot.tag = element_text(face="plain")), 
                                        nrow=1)
# ggsave(file.path(DIR_FIGURES, "exp_correlated_both.pdf"), fig_correlated_both, width = 8, height = 4)
```


# Between-view correction
## Tiles in contingency table
```{r warning=FALSE}
source("run_exp_num_size.R", chdir = TRUE)
```

```{r}
a_fwer = 0.1
list_of_funs = list(
  fwer_investing = function(pv) do_fwer_investing(pv, a_fwer),
  addis = function(pv) onlineFDR::ADDIS(pv, a_fwer), 
  alpha_spending = function(pv) onlineFDR::Alpha_spending(pv, a_fwer))

exp_df = exp_num_size %>% 
  apply_alpha_investing_funs(list_of_funs) %>% 
  dplyr::mutate(num_significant_fwer = purrr::map_int(fwer_investing, ~sum(.$pv <= .$a_t)), 
                num_significant_addis = purrr::map_int(addis, ~sum(.$pval <= .$alphai)), 
                num_significant_alpha_spending = purrr::map_int(alpha_spending, ~sum(.$pval <= .$`alpha...gammai`)), 
                pct_significant_fwer = num_significant_fwer / num_tile,
                pct_significant_addis = num_significant_addis / num_tile, 
                pct_significant_alpha_spending = num_significant_alpha_spending / num_tile) %>% 
  dplyr::select(num_tile, size_tile, starts_with("pct_significant")) %>% 
  tidyr::pivot_longer(starts_with("pct_significant")) %>% 
  dplyr::mutate(name = factor(name, 
                              levels = c("pct_significant_alpha_spending", "pct_significant_addis", "pct_significant_fwer"), 
                          labels = c("Alpha spending", "ADDIS", "FWER investing"))) 

fig_num_size = ggplot(exp_df) + theme_minimal() + 
  geom_tile(aes(num_tile, size_tile, fill=value), width=25) + 
  scale_fill_viridis_c(limits=c(0,1), direction=1, labels=scales::percent_format()) + 
  facet_wrap(~name) + 
  scale_x_continuous(breaks = unique(exp_df$num_tile)) + 
  # scale_y_continuous(breaks = unique(exp_df$size_tile)) + 
  scale_y_continuous(breaks = c(10, 20, 30, 40, 50)) + 
  labs(x = "Number of true patterns", 
       y = "Size of true patterns", 
       fill = "Recall")+ 
  theme(legend.position = "right", 
        panel.grid.minor = element_blank())

fig_num_size
# ggsave(file.path(DIR_FIGURES, "exp_num_size.pdf"), fig_num_size, width = 5, height = 3)
```

## Tile overlap in contingency table
```{r}
source("run_exp_overlap.R", chdir = TRUE)
```

```{r}
fig_overlap = exp_overlap$result %>% 
  mutate(s = -log(pv), 
         size_pattern = r1 - r0 + 1, 
         is_significant = pv <= 0.1) %>% 
  arrange(s) %>% 
ggplot() + theme_minimal() +
  geom_point(aes(size_pattern, pct_signal, color=s), alpha=0.8, size=1) + 
  scale_color_viridis_c(direction=1) + 
  scale_y_continuous(labels=scales::percent_format()) + 
  expand_limits(x=c(0,1), y=c(0,1)) + 
  labs(y = "Overlap with true pattern", 
       x = "Size of selected pattern", 
       color = "-log(p)") + 
  theme(legend.position = "right")

fig_overlap
#ggsave(file.path(DIR_FIGURES, "exp_overlap.pdf"), fig_overlap, width = 4, height = 3)
```

```{r}
fig_power_both = ggpubr::ggarrange(fig_num_size + 
                                     labs(tag="(a)") + 
                                     theme(plot.tag.position = "left", 
                                           plot.tag = element_text(margin=margin(0, 10, 0, 0))),  
                                   fig_overlap + 
                                     labs(tag="(b)") + 
                                     theme(plot.tag.position = "left", 
                                           plot.tag = element_text(margin=margin(0, 10, 0, 0))), 
                                   nrow=2)
fig_power_both
# ggsave(file.path(DIR_FIGURES, "exp_power_both.pdf"), fig_power_both, width = 5, height = 4)
```

