---
title: "Use-cases"
author: Rafael Savvides 
email: rafael.savvides@helsinki.fi
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

This notebook reproduces the figures in the "Use-cases" section.

# Init

```{r message=F}
source("funs/read_data.R") 
source("funs/plot.R")
source("funs/null_distributions.R")
source("funs/banana_utils.R")
source("funs/pvalue.R")
source("funs/tester.R")
aq = read_aq("data/AirQualityUCI.csv")
german = read_german("data/socio_economics_germany_full.rds")
smear = read_smear_all("data/banana-data.rds", "data/DMPS_Event_Classification.txt")
DIR_FIGURES = "figures"
```

# Motivating Example (time series)

```{r}
aq_day1 = aq[format(aq$timestamp, "%Y-%m-%d") == "2004-03-25", ]
n_day1 = nrow(aq_day1)
i_outlier = which.max(aq_day1$CO.GT.)
sample_gp <- train_gp(x_test = aq_day1$timestamp, 
                      x_train = aq_day1$timestamp[i_outlier], 
                      y_train = aq_day1$CO.GT.[i_outlier], 
                      kern = function(x, y) kernel_sqexp(x, y, l = 3600*6))

set.seed(42)
surrogates_gp_prior <- sample_gp$prior(25)
surrogates_gp_post <- sample_gp$post(25)

ylim = range(c(aq_day1$CO.GT., surrogates_gp_post, surrogates_gp_prior))

fig_ts_prior <- plot_ts_gg(aq_day1$timestamp, aq_day1$CO.GT., surrogates_gp_prior) + ylim(ylim) + scale_x_datetime(date_labels="%H:%M")
fig_ts_post <- plot_ts_gg(aq_day1$timestamp, aq_day1$CO.GT., surrogates_gp_post) + ylim(ylim) + scale_x_datetime(date_labels="%H:%M")

fig_ts_prior
fig_ts_post
```
```{r}
set.seed(42)
value_at_every_time_instance <- function(x) x 
test_ts_prior <- tester(aq_day1$CO.GT., 
                     n_resample = 5000, 
                     test_stat = value_at_every_time_instance, 
                     sample_from_null = sample_gp$prior, samples_test_statistics = T)

test_ts_post <- tester(aq_day1$CO.GT., 
                    n_resample = 5000, 
                    test_stat = function(x) x, 
                    sample_from_null = sample_gp$post, samples_test_statistics = T)
```



```{r}
ylim=range(c(aq_day1$CO.GT., surrogates_gp_prior, surrogates_gp_post))
gg_x_breaks=scale_x_continuous(breaks=c(1,7,13,19,25))
fig_ts_prior_test_stat = plot_test_stat(aq_day1$CO.GT., surrogates_gp_prior) + ylim(ylim) + gg_x_breaks
fig_ts_post_test_stat = plot_test_stat(aq_day1$CO.GT., surrogates_gp_post)+ ylim(ylim) + gg_x_breaks
fig_ts_prior_pv = plot_pvalues(test_ts_prior) + gg_x_breaks
fig_ts_post_pv = plot_pvalues(test_ts_post)  + gg_x_breaks

fig_ts_combined = ggpubr::ggarrange(fig_ts_prior + 
                                      labs(tag="(a)") + 
                                      theme(plot.tag.position = "left", 
                                            plot.tag = element_text(margin = margin(0, 10, 0, 0))), 
                                    fig_ts_post + 
                                      labs(tag="(d)") + 
                                      theme(plot.tag.position = "left", 
                                            plot.tag = element_text(margin = margin(0, 0, 0, 0))), 
                                    fig_ts_prior_test_stat + 
                                      labs(tag="(b)", x="", y="Test statistic value") + 
                                      theme(plot.tag.position = "left", 
                                            plot.tag = element_text(margin = margin(0, 10, 0, 0))), 
                                    fig_ts_post_test_stat + 
                                      labs(tag="(e)", x="", y="") + 
                                      theme(plot.tag.position = "left", 
                                            plot.tag = element_text(margin = margin(0, 0, 0, 0))), 
                                    fig_ts_prior_pv + 
                                      labs(tag="(c)")+ 
                                      theme(plot.tag.position = "left", 
                                            plot.tag = element_text(margin = margin(0, 10, 0, 0))), 
                                    fig_ts_post_pv + 
                                      labs(tag="(f)", y="")+ 
                                      theme(plot.tag.position = "left", 
                                            plot.tag = element_text(margin = margin(0, 0, 0, 0))), 
                                    nrow=3, ncol=2, 
                                    common.legend = TRUE, legend="bottom")
fig_ts_combined
#ggsave(file.path(DIR_FIGURES, "ts-combined.pdf"), fig_ts_combined, width=10, height=6.5) # For figure* environment.
#ggsave(file.path(DIR_FIGURES, "ts-combined.pdf"), fig_ts_combined, width=8, height=8)
```

# Time series - Abrupt change

```{r}
aq_day2 = aq[format(aq$timestamp, "%Y-%m-%d") == "2004-03-17", ]
aq_split = split(aq$CO.GT., as.factor(strptime(aq$timestamp, "%Y-%m-%d")))
aq_split = aq_split[sapply(aq_split, length)==24 & sapply(aq_split, function(x) !all(is.na(x)))]

i_abrupt_change = c(8, 10) # Indices for 07:00 and 09:00

set.seed(42)
surrogates_historical = sample(aq_split, 25)

fig_ts_history = plot_ts_gg(aq_day2$timestamp, aq_day2$CO.GT., surrogates_historical) + 
  geom_vline(xintercept=aq_day2$timestamp[i_abrupt_change], lty=2, lwd=0.3) 

fig_ts_history
```

```{r warning=FALSE}
diff_in_interval <- function(x, t1 = a, t2 = b) x[t2] - x[t1] 
diff_in_all_2h_intervals <- function(x) apply_to_intervals(as.matrix(x),
                                                           f = diff_in_interval,
                                                           L = 2,
                                                           returnNamed = T)

test_ts_diff_all_2h_intervals <- tester2(X_obs=aq_day2$CO.GT., 
                                         null_samples = aq_split,
                                         test_stat = diff_in_all_2h_intervals)
# Replace indices with hours (for example, 1 becomes 0)
names(test_ts_diff_all_2h_intervals$t0) = sapply(lapply(strsplit(names(test_ts_diff_all_2h_intervals$t0), "-"), function(x) as.numeric(x)-1), function(x) paste0(x, collapse="-"))
test_to_pvalue(test_ts_diff_all_2h_intervals, use_minp = TRUE)
```

```{r}
fig_ts_history_test_stat = plot_test_stat(test_ts_diff_all_2h_intervals$t0, 
                                          test_ts_diff_all_2h_intervals$t_null, 
                                          show_x_labels = TRUE)
fig_ts_history_pv = plot_pvalues(test_ts_diff_all_2h_intervals, TRUE) + labs(x = "Test statistic (2-hour differences)")
fig_ts_history_combined = ggpubr::ggarrange(fig_ts_history + 
                                              labs(tag="(a)") + 
                                              theme(plot.tag.position = "left", 
                                                    plot.tag = element_text(margin = margin(0, 15, 0, 0))), 
                                            fig_ts_history_test_stat + 
                                              labs(x="", tag="(b)") + 
                                              theme(plot.tag.position = "left", 
                                                    plot.tag = element_text(margin = margin(0, 15, 40, 0))),
                                            fig_ts_history_pv + 
                                              labs(tag="(c)") + 
                                              theme(plot.tag.position = "left", 
                                                    plot.tag = element_text(margin = margin(0, 15, 70, 0))), 
                                            nrow=3, legend="bottom")
fig_ts_history_combined
#ggsave(file.path(DIR_FIGURES, "ts-history-combined.pdf"), fig_ts_history_combined, width=6, height=7)
```

# Scatterplot - Scagnostics

```{r}
j_scag <- c(28, 7)
tile_german = tiling(n = nrow(german), m = ncol(german))
sample_permutations = function(n=1) replicate(tile_german$permutedata(german)[,j_scag], n=n, simplify=F) 

set.seed(42)
surrogates_perm <- sample_permutations(n=10)
fig_german_skewed = scatterplot_gg(german[, j_scag], surrogates_perm)
fig_german_skewed
```

```{r}
set.seed(42)
test_german_scag <- tester(X_obs = german[,j_scag], 
                           n_resample = 1000, 
                           test_stat = scag, 
                           sample_from_null = function() tile_german$permutedata(german)[,j_scag])
test_to_pvalue(test_german_scag)
```

# Scatterplot - Dense region of points

```{r}
set.seed(42)
split_ratio <- 0.5
idx_split <- sample(nrow(german), size = round(nrow(german) * split_ratio))
# idx_split <- c(377,386,118,340,262,212,300,55,266,285,185,289,374,102,184,400,388,47,188,221,355,405,411,369,32,199,151,349,172,321,282,310,148,260,2,315,3,78,409,229,142,162,14,360,159,352,325,234,354,225,121,126,144,382,370,268,242,61,93,182,238,345,404,198,296,66,94,286,239,83,15,48,74,163,67,243,376,361,384,1,194,53,119,213,255,402,77,30,28,99,215,333,338,298,295,233,106,339,365,332,196,68,311,362,291,348,227,224,412,383,398,252,226,136,160,319,303,105,180,337,318,120,167,171,208,114,263,275,320,206,328,170,177,408,237,161,306,396,210,401,41,22,335,274,197,219,46,251,375,40,189,85,203,103,176,200,49,8,35,173,236,139,390,50,133,45,112,264,29,350,280,100,241,115,399,33,195,140,186,294,329,257,73,60,281,228,288,179,366,65,44,174,244,220,16,12,344,25,297,156,394,110,363,364,278,92) # KDD version with R 3.5.2

german_viz <- german[idx_split, ]
german_test <- german[-idx_split, ]

pvec_t1 <- matrix(ncol = 2,
                  byrow = T, 
                  data = c(-0.20812984,0.104020433,0.05990979, -0.099812793,-0.24639380, -0.117946512,-0.11624038,-0.287016907,0.27903707,0.130979455,-0.23985513, -0.101385960,0.05940001,-0.253213364,0.19738100,0.135532251,0.14333147,0.266455176,-0.06348592,-0.273316607,0.06425944,-0.161007169,-0.27982946, -0.026321798,0.23709035,-0.082338519,0.21782876,0.049192671,-0.08232096, -0.230579644,-0.10346176,-0.179110660,-0.21100813,-0.128821268,0.13862144, -0.058078100,0.04182044,-0.001105998,0.01557894, -0.256028765,-0.21179466,0.241864953,-0.06820454,0.235701968,-0.18061247,0.211785490,-0.20709077,0.142938684,0.01938115,0.282079429,0.18008659, -0.248325281,-0.01936813,-0.046666645,0.07365535,-0.286046537,0.22844881,-0.106202163,0.13828398,-0.045914802,0.29663816,0.030275195,0.29013785,0.042963275), 
                  dimnames = list(colnames(german_test), NULL))

region_t1 = matrix(ncol = 2, 
                   c(6.8065932240526, 4.61553118616816, 3.09131201089206, 
2.25767139982178, 1.7412607067882, 1.4577873902498, 2.41541103192371, 
6.01864650561476, 2.94003855122172, 1.64054073095589, 1.33335608891392, 
1.66517927051323, 3.22851970685852, 4.52009305036682, 4.91313090141144, 
4.76066730552199))

R_region_t1_viz = points_in_selection(german_viz %*% pvec_t1, region_t1)
R_region_t1_test = points_in_selection(german_test %*% pvec_t1, region_t1)

pvec_t2 <- matrix(ncol = 2, 
                  byrow = T, 
                  data = c(-0.182898728,0.046784628,0.086336015,-0.290675215,-0.097171720,0.089453203,0.146354042,0.196681478,0.237927378,0.090368043,-0.145360710,-0.089451254,0.211901628,0.086380488,0.065868274,-0.395870364,-0.185631925,-0.106229409,0.153883305,0.299982364,0.137294777,0.083407338,-0.281658636,-0.118886857,0.225993505,0.146757383,0.128587587,-0.308107602,0.101163722,0.187058399,0.044837537,0.120987483,-0.072485055,0.136796134,0.123300841,-0.145878983,0.024676426,-0.097395808,0.187339783,0.187941587,-0.266937912,-0.011652182,-0.184139352,-0.202973244,-0.239467629,0.049770157,-0.218674164,0.149115730,-0.209912778,-0.043875803,0.245354418,-0.048478112,0.004498666,-0.006959673,0.227218980,0.118740846,0.216991342,-0.200672373,0.119424376,-0.216416438,0.195314932,-0.347961240,0.207808410,-0.142741432),
                  dimnames = list(colnames(german_test), NULL))

region_t2 = matrix(ncol = 2, 
                   c(6.89860263463784, 6.47771361476198, 4.37339947293676, 
3.92867440157959, 3.62494053588073, 2.68682377957273, 1.90257772993235, 
1.22948100427482, 3.01055222909178, 5.23063985787254, 6.09604470247955, 
6.89526317236999, -1.28949855890036, -2.60917207000071, -3.42127904643762, 
-3.09826135455714, -2.83162065173341, -1.45458750589257, -0.166128882540439, 
3.12198358286681, 4.78208627209424, 5.74747321445642, 4.58895730565457, 
0.964308106653392))

tile_german_test <- tiling(n = nrow(german_test), m = ncol(german_test))
sample_perm_t1 = function() tile_german_test$permutedata(german_test) 
tile_german_test_t2 = tile_german_test$copy()
tile_german_test_t2$addtile(R=R_region_t1_test, 
                            C=1:ncol(german_test))
sample_perm_t2 = function() tile_german_test_t2$permutedata(german_test) 
```

```{r}
set.seed(42)
surrogates_perm_t1 = replicate(sample_perm_t1(), 
                        n = 1000, 
                        simplify = F)

fig_german_view1 = scatterplot_gg(project(german_viz, pvec_t1), 
                                  lapply(surrogates_perm_t1[1:10], function(X) project(X, pvec_t1)), 
                                  region_t1)
fig_german_view1
# ggsave(file.path(DIR_FIGURES, "german-view1.pdf"), fig_german_view1, width=4, height=4)
```

```{r}
set.seed(42)

test_german_view1 <- tester(
  X_obs = german_test, 
  n_resample = 1000, 
  test_stat = num_points_in_selection, 
  sample_from_null = sample_perm_t1, 
  pvec = pvec_t1, 
  region = region_t1)

test_to_pvalue(test_german_view1)
```


```{r}
df2=as.data.frame(project(german_viz, pvec_t2))
fig_german_view2 = scatterplot_gg(df2, 
                                  lapply(surrogates_perm_t1[1:10], function(X) project(X, pvec_t2)), 
                                  region_t2) + 
                    geom_point(data=df2[R_region_t1_viz, ], 
                               aes(x=df2[R_region_t1_viz,1], y=df2[R_region_t1_viz,2]),
                               shape="o", size=4, col="darkred", alpha=0.6)
fig_german_view2
#ggsave(file.path(DIR_FIGURES, "german-view2.pdf"), fig_german_view2, width=4, height=4)
```
```{r}
set.seed(42)

test_german_view2 <- tester(
  X_obs = german_test, 
  n_resample = 1000, 
  test_stat = num_points_in_selection, 
  sample_from_null = sample_perm_t2, 
  pvec = pvec_t2, 
  region = region_t2)

test_to_pvalue(test_german_view2)
```

```{r}
fig_german_both = ggpubr::ggarrange(fig_german_view1 + 
                                      labs(tag="(a)") + 
                                      theme(axis.title = element_text(size=7), 
                                            plot.tag.position = "bottom", 
                                            plot.tag = element_text(margin = margin(10, 0, 0, 0))), 
                                    fig_german_view2 + 
                                      labs(tag="(b)") + 
                                      theme(axis.title = element_text(size=7), 
                                            plot.tag.position = "bottom", 
                                            plot.tag = element_text(margin = margin(10, 0, 0, 0))), 
                                    nrow=1)
fig_german_both
#ggsave(file.path(DIR_FIGURES, "german-both.pdf"), fig_german_both, width=6, height=3)
```


# Heatmap - Banana shape

```{r}
smear_day1 <- smear$data[format(smear$data$timestamp, "%Y-%m-%d") %in% "2010-07-23", ] 
smear_day2 <- smear$data[format(smear$data$timestamp, "%Y-%m-%d") %in% "2010-12-10", ] # Non-event day
set.seed(42)
smear_test_params = make_banana_test_params(smear_df = smear$data, 
                                            i_null = smear$i_non_event, 
                                            test_stat_params = list(fun = function(x) quantile(x, 0.25, na.rm=T, names=F), 
                                                                    line_type = "rising", 
                                                                    n_lines = 1000))
```

Event vs non-event day:
```{r}
fig_smear_day1 <- plot_banana(smear_day1)
fig_smear_day1

fig_smear_day2 = plot_banana(smear_day2)
fig_smear_day2
```

```{r}
file_test_smear_day1 = "results/test_smear_day1.rds"
if (file.exists(file_test_smear_day1)) {
  test_smear_day1 = readRDS(file_test_smear_day1)
} else {
  test_smear_day1 <- tester2(X_obs = as.matrix(smear_day1[,-1]), 
                             null_samples = smear_test_params$null_samples, 
                             test_stat = smear_test_params$test_stat)
  saveRDS(test_smear_day1, file_test_smear_day1)
}
i_lines_signif_day1 = test_to_pvalue(test_smear_day1) <= 0.1
```
```{r}
file_test_smear_day2 = "results/test_smear_day2.rds"
if (file.exists(file_test_smear_day2)) {
  test_smear_day2 = readRDS(file_test_smear_day2)
} else {
  test_smear_day2 <- tester2(X_obs = as.matrix(smear_day2[,-1]), 
                             null_samples = smear_test_params$null_samples, 
                             test_stat = smear_test_params$test_stat)
  saveRDS(test_smear_day2, file_test_smear_day2)
}

i_lines_signif_day2 = test_to_pvalue(test_smear_day2) <= 0.1
```

```{r}
smear_lines_to_test = smear_test_params$test_stat_params$lines_to_test

fig_smear_day1_lines = plot_lines(plot_lines(fig_smear_day1, 
                                             smear_lines_to_test, 
                                             alpha=0.1), 
                                  smear_lines_to_test[i_lines_signif_day1,], 
                                  alpha=0.3, color="darkblue")
fig_smear_day2_lines = plot_lines(plot_lines(fig_smear_day2, 
                                             smear_lines_to_test, 
                                             alpha=0.1), 
                                  smear_lines_to_test[i_lines_signif_day2,], 
                                  alpha=0.3, color="darkblue")
fig_smear_day1_lines
fig_smear_day2_lines
```
```{r}
fig_smear = ggpubr::ggarrange(fig_smear_day1 + 
                                labs(tag="(a)") + 
                                theme(plot.tag.position = "left", 
                                      plot.tag = element_text(margin = margin(0, 10, 20, 0))), 
                              fig_smear_day2 + 
                                labs(y="", tag="(b)") + 
                                theme(plot.tag.position = "left", 
                                      plot.tag = element_text(margin = margin(0, 0, 20, 0))), 
                              fig_smear_day1_lines+ 
                                labs(tag="(c)") + 
                                theme(plot.tag.position = "left", 
                                      plot.tag = element_text(margin = margin(0, 10, 20, 0))), 
                              fig_smear_day2_lines + 
                                labs(y="", tag="(d)") + 
                                theme(plot.tag.position = "left", 
                                      plot.tag = element_text(margin = margin(0, 0, 20, 0))), 
                              common.legend = T, legend="bottom", nrow=2, ncol=2)
fig_smear
# ggsave(file.path(DIR_FIGURES, "banana-teaser.pdf"), fig_smear, width=16, height=6)
# ggsave(file.path(DIR_FIGURES, "banana-teaser.pdf"), fig_smear, width=10, height=4)
```

